#spring 基础配置文件，dev 表示开发环境， test 表示测试环境， product 表示生产环境
server:
  port: 18762
spring:
  profiles:
    active: dev
  application:
    name: uc-server
  mvc:
    view:
      prefix: /
      suffix: .html
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.hopedove.ucserver.vo
eureka:
  client:
    registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
---
#开发环境配置
#容器端口
#server:
#  port: 18762
spring:
  profiles: dev
  datasource:
    name: test
    url: jdbc:mysql://101.200.162.47:3306/ly2?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 1QAzxsw@
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    timeout: 5000
    jedis:
      pool:
        max-active: 200
        max-wait: 1
        max-idle: 10
        min-idle: 0
logging:
  config: classpath:logback-dev.xml
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:18761/eureka/
fdfs:
  connect-timeout: 3000
  so-timeout: 3000
  tracker-list: 115.28.145.79:22122
  pool:
    jmx-enabled: false

filePath: D://
# Socket配置
socket:
  # 监听端口 2323
  port: 9002
  # 线程池 - 保持线程数 20
  pool-keep: 20
  # 线程池 - 核心线程数 10
  pool-core: 10
  # 线程池 - 最大线程数 20
  pool-max: 30
  # 线程队列容量 10
  pool-queue-init: 10
  #serverId
  server-ip: 127.0.0.1
  #serverport
  server-port: 9006
logsLimit: 20000
---
#测试环境配置
#容器端口
#server:
#  port: 18762
spring:
  profiles: test
  datasource:
    name: test
    url: jdbc:sqlserver://47.105.107.250:1433;databasename=zhouwx_gpck
    username: sa
    password: Root123abc@hd
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  redis:
    database: 1
    host: localhost
    port: 6379
    timeout: 5000
#    password: password
    jedis:
      pool:
        max-active: 200
        max-wait: 1
        max-idle: 10
        min-idle: 0
logging:
  config: classpath:logback-test.xml
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
fdfs:
  connect-timeout: 3000
  so-timeout: 3000
  tracker-list: 115.28.145.79:22122
  pool:
    jmx-enabled: false
---
#产线环境配置1
spring:
  profiles: prod1
  datasource:
    name: test
    url: jdbc:mysql://127.0.0.1:3306/ly2?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 1QAzxsw@
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 5000
    initialSize: 100
    maxWait: 60000
    minIdle: 100
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    timeout: 5000
    jedis:
      pool:
        max-active: 5000
        max-wait: 500
        max-idle: 200
        min-idle: 0
  activemq:
    broker-url: tcp://127.0.0.1:61616
    maximum-redeliveries: 0
logging:
  config: classpath:logback-prod.xml
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
fdfs:
  connect-timeout: 30000
  so-timeout: 30000
  tracker-list:
    - 10.10.31.86:22122

  pool:
    jmx-enabled: false
filePath: /home/files
socket:
  # 监听端口 2323
  port: 9002
  # 线程池 - 保持线程数 20
  pool-keep: 20
  # 线程池 - 核心线程数 10
  pool-core: 10
  # 线程池 - 最大线程数 20
  pool-max: 20
  # 线程队列容量 10
  pool-queue-init: 10
  #serverId
  server-ip: 127.0.0.1
  #serverport
  server-port: 9003
logsLimit: 10000
---


spring:
  profiles: preprod1
  datasource:
    name: test
    url: jdbc:sqlserver://192.168.1.38:1433;databasename=guangpick
    username: guangpiUser
    password: gpr.20191008
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    timeout: 5000
    jedis:
      pool:
        max-active: 200
        max-wait: 1
        max-idle: 10
        min-idle: 0
logging:
  config: classpath:logback-dev.xml
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
fdfs:
  connect-timeout: 3000
  so-timeout: 3000
  tracker-list: 115.28.145.79:22122
  pool:
    jmx-enabled: false

---
#申州测试环境配置1
spring:
  profiles: sztest
  datasource:
    name: test
    url: jdbc:sqlserver://192.168.101.4:1433;databasename=guangpick
    username: wlb
    password: wuliuban
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    filters: stat
    maxActive: 5000
    initialSize: 100
    maxWait: 60000
    minIdle: 100
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  redis:
    database: 0
    host: 10.10.31.44
    port: 6379
    timeout: 5000
    jedis:
      pool:
        max-active: 5000
        max-wait: 500
        max-idle: 200
        min-idle: 0
logging:
  config: classpath:logback-prod.xml
eureka:
  client:
    serviceUrl:
      defaultZone: http://10.10.31.44:8761/eureka/
fdfs:
  connect-timeout: 30000
  so-timeout: 30000
  tracker-list:
    - 10.10.31.44:22122

  pool:
    jmx-enabled: false

---
#测试环境配置
#容器端口
#server:
#  port: 8762
spring:
  profiles: aliyun
  datasource:
    name: test
    url: jdbc:sqlserver://localhost:1433;databasename=zhouwx_gpck
    username: sa
    password: Root123abc@hd
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  redis:
    database: 1
    host: localhost
    port: 6379
    timeout: 5000
#    password: password
    jedis:
      pool:
        max-active: 200
        max-wait: 1
        max-idle: 10
        min-idle: 0
logging:
  config: classpath:logback-test.xml
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
fdfs:
  connect-timeout: 3000
  so-timeout: 3000
  tracker-list: 115.28.145.79:22122
  pool:
    jmx-enabled: false


---
#越南产线环境配置1
spring:
  profiles: dlprod
  datasource:
    name: test
    url: jdbc:sqlserver://10.10.115.22:1433;databasename=guangpick
    username: guangpiuser
    password: gpr.20191008
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    filters: stat
    maxActive: 5000
    initialSize: 100
    maxWait: 60000
    minIdle: 100
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  redis:
    database: 0
    host: 10.10.115.69
    port: 6379
    timeout: 5000
    jedis:
      pool:
        max-active: 5000
        max-wait: 500
        max-idle: 200
        min-idle: 0
logging:
  config: classpath:logback-prod.xml
eureka:
  client:
    serviceUrl:
      defaultZone: http://10.10.115.69:8761/eureka/
fdfs:
  connect-timeout: 30000
  so-timeout: 30000
  tracker-list:
    - 10.10.115.69:22122

  pool:
    jmx-enabled: false
