#spring 基础配置文件，dev 表示开发环境， test 表示测试环境， product 表示生产环境
server:
  port: 18764
  servlet:
    context-path: /blw
spring:
  profiles:
    active: dev
  application:
    name: gateway-server
  mvc:
    view:
      prefix: /
      suffix: .html
    throw-exception-if-no-handler-found: true
    resources:
      add-mappings: false
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 200MB
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.hopedove.gatewayserver.vo
ribbon:
  ReadTimeout: 50000
  ConnectTimeout: 300000
zuul:
  host:
    connect-timeout-millis: 30000
    socket-timeout-millis: 30000
  routes:
    uc:
      path: /uc/**
      serviceId: uc-server
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 600000
#熔断器失败100个   后短路默认是20个 短路默认时间为5秒            
#      circuitBreaker:
#        requestVolumeThreshold: 100
#feign核心线程池的数量 默认为10这边改为100                
#  threadpool:
#    default:
#      coreSize: 30          
eureka:
  client:
    registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
---
#开发环境配置
#容器端口
spring:
  profiles: dev
  datasource:
    name: test
    url: jdbc:mysql://127.0.0.1:3306/warning?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
logging:
  config: classpath:logback-dev.xml
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:18761/eureka/
gateway-config:
  rsaPrivateKey: MIICdwIBADANBgkqhkiG9w0BAQEFAASCAmEwggJdAgEAAoGBAJ4QScPdDOqFr030Ue4FdBoLg3ixyA3s92U5M0xOSbb+DSdlBO54fRPGmw1hkoZHeQUDP+dYsP5JMJRyHfYFj0ycUX8pke3GarbLy5VdrAyEkrvayn5aWWB0VtcgdI95HRv6T71DyrYAKjZbgq84xEwmtnZCMM3MzeQNKh5xF/BjAgMBAAECgYBXI5+nDRxrxluI3GK2l+cT3LkUNt6VXshc05YGQTq+WXyi9Twsw9wgpOMiE2KWCJ0dOFdokSqyZWMU03zU/ueqclHe54R07DyC/3YIIGKq6pPi/wu1qBOCPNxf0kITcgBE/JKRb/c79o4srV3UlLXXi6LV4YcOQHf+NLFNb7+jcQJBAOmk+YjEj1Pow4hDoyngTx351bgLtl83VsFhxfmwooumzMNksp9jiWkPLAgtIDqwVvs4aZL/WmV65lgdmzCzXFUCQQCtL/4HmoGEBuwxUF7DhvVhuxxj2zBsUrL0l9+TnSfWChehNENoWwQTo8vggKrSEug/5V/EQkX9H+ZOU5C/xNHXAkEAtcIgWTRIJ8eQrSWo/b/A7JnZl8aMxj+/nsrX/2lY2fkVm/9vMa12TSN/ZpDsXJun3uFAyBkcEovsO6o0e0tczQJAOSYPE38+ocyPAC7fNnJAYsGVurXHotcfSmsbUeCYFp858O4IGFWAYOK6EhkjRTMMBJmyIlckNUTjgJE+wKk3/QJBAN/E05QAv8YlS8NVfqylS9OCcbuH+pSkYJHc14P7+cNG2mrcWh5Y10QWhV+aHruutOLTtBQBN71tsvUu2l3O4Go=
  rsaPublicKey: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCeEEnD3Qzqha9N9FHuBXQaC4N4scgN7PdlOTNMTkm2/g0nZQTueH0TxpsNYZKGR3kFAz/nWLD+STCUch32BY9MnFF/KZHtxmq2y8uVXawMhJK72sp+WllgdFbXIHSPeR0b+k+9Q8q2ACo2W4KvOMRMJrZ2QjDNzM3kDSoecRfwYwIDAQAB
---
#测试环境配置
spring:
  profiles: test
  datasource:
    name: test
    url: jdbc:sqlserver://127.0.0.1:3306;databasename=warning
    username: sa
    password: Root123abc@hd
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
logging:
  config: classpath:logback-test.xml
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:18761/eureka/
gateway-config:
  rsaPrivateKey: MIICdwIBADANBgkqhkiG9w0BAQEFAASCAmEwggJdAgEAAoGBAJ4QScPdDOqFr030Ue4FdBoLg3ixyA3s92U5M0xOSbb+DSdlBO54fRPGmw1hkoZHeQUDP+dYsP5JMJRyHfYFj0ycUX8pke3GarbLy5VdrAyEkrvayn5aWWB0VtcgdI95HRv6T71DyrYAKjZbgq84xEwmtnZCMM3MzeQNKh5xF/BjAgMBAAECgYBXI5+nDRxrxluI3GK2l+cT3LkUNt6VXshc05YGQTq+WXyi9Twsw9wgpOMiE2KWCJ0dOFdokSqyZWMU03zU/ueqclHe54R07DyC/3YIIGKq6pPi/wu1qBOCPNxf0kITcgBE/JKRb/c79o4srV3UlLXXi6LV4YcOQHf+NLFNb7+jcQJBAOmk+YjEj1Pow4hDoyngTx351bgLtl83VsFhxfmwooumzMNksp9jiWkPLAgtIDqwVvs4aZL/WmV65lgdmzCzXFUCQQCtL/4HmoGEBuwxUF7DhvVhuxxj2zBsUrL0l9+TnSfWChehNENoWwQTo8vggKrSEug/5V/EQkX9H+ZOU5C/xNHXAkEAtcIgWTRIJ8eQrSWo/b/A7JnZl8aMxj+/nsrX/2lY2fkVm/9vMa12TSN/ZpDsXJun3uFAyBkcEovsO6o0e0tczQJAOSYPE38+ocyPAC7fNnJAYsGVurXHotcfSmsbUeCYFp858O4IGFWAYOK6EhkjRTMMBJmyIlckNUTjgJE+wKk3/QJBAN/E05QAv8YlS8NVfqylS9OCcbuH+pSkYJHc14P7+cNG2mrcWh5Y10QWhV+aHruutOLTtBQBN71tsvUu2l3O4Go=
  rsaPublicKey: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCeEEnD3Qzqha9N9FHuBXQaC4N4scgN7PdlOTNMTkm2/g0nZQTueH0TxpsNYZKGR3kFAz/nWLD+STCUch32BY9MnFF/KZHtxmq2y8uVXawMhJK72sp+WllgdFbXIHSPeR0b+k+9Q8q2ACo2W4KvOMRMJrZ2QjDNzM3kDSoecRfwYwIDAQAB
---
#生产环境配置
server:
  port: 18764
spring:
  profiles: prod1
  datasource:
    name: test
    url: jdbc:mysql://127.0.0.1:3306/warning?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 1QAzxsw@
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 5000
    initialSize: 100
    maxWait: 60000
    minIdle: 200
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
logging:
  config: classpath:logback-prod.xml
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
gateway-config:
  rsaPrivateKey: MIICdwIBADANBgkqhkiG9w0BAQEFAASCAmEwggJdAgEAAoGBAJ4QScPdDOqFr030Ue4FdBoLg3ixyA3s92U5M0xOSbb+DSdlBO54fRPGmw1hkoZHeQUDP+dYsP5JMJRyHfYFj0ycUX8pke3GarbLy5VdrAyEkrvayn5aWWB0VtcgdI95HRv6T71DyrYAKjZbgq84xEwmtnZCMM3MzeQNKh5xF/BjAgMBAAECgYBXI5+nDRxrxluI3GK2l+cT3LkUNt6VXshc05YGQTq+WXyi9Twsw9wgpOMiE2KWCJ0dOFdokSqyZWMU03zU/ueqclHe54R07DyC/3YIIGKq6pPi/wu1qBOCPNxf0kITcgBE/JKRb/c79o4srV3UlLXXi6LV4YcOQHf+NLFNb7+jcQJBAOmk+YjEj1Pow4hDoyngTx351bgLtl83VsFhxfmwooumzMNksp9jiWkPLAgtIDqwVvs4aZL/WmV65lgdmzCzXFUCQQCtL/4HmoGEBuwxUF7DhvVhuxxj2zBsUrL0l9+TnSfWChehNENoWwQTo8vggKrSEug/5V/EQkX9H+ZOU5C/xNHXAkEAtcIgWTRIJ8eQrSWo/b/A7JnZl8aMxj+/nsrX/2lY2fkVm/9vMa12TSN/ZpDsXJun3uFAyBkcEovsO6o0e0tczQJAOSYPE38+ocyPAC7fNnJAYsGVurXHotcfSmsbUeCYFp858O4IGFWAYOK6EhkjRTMMBJmyIlckNUTjgJE+wKk3/QJBAN/E05QAv8YlS8NVfqylS9OCcbuH+pSkYJHc14P7+cNG2mrcWh5Y10QWhV+aHruutOLTtBQBN71tsvUu2l3O4Go=
  rsaPublicKey: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCeEEnD3Qzqha9N9FHuBXQaC4N4scgN7PdlOTNMTkm2/g0nZQTueH0TxpsNYZKGR3kFAz/nWLD+STCUch32BY9MnFF/KZHtxmq2y8uVXawMhJK72sp+WllgdFbXIHSPeR0b+k+9Q8q2ACo2W4KvOMRMJrZ2QjDNzM3kDSoecRfwYwIDAQAB

---
#本地生产环境配置
server:
  port: 8764
spring:
  profiles: sztest
  datasource:
    name: test
    url: jdbc:sqlserver://192.168.88.41:1433;databasename=szstTest
    username: testszst
    password: tt.123
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    filters: stat
    maxActive: 5000
    initialSize: 100
    maxWait: 60000
    minIdle: 200
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
logging:
  config: classpath:logback-dev.xml
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
gateway-config:
  rsaPrivateKey: MIICdwIBADANBgkqhkiG9w0BAQEFAASCAmEwggJdAgEAAoGBAJ4QScPdDOqFr030Ue4FdBoLg3ixyA3s92U5M0xOSbb+DSdlBO54fRPGmw1hkoZHeQUDP+dYsP5JMJRyHfYFj0ycUX8pke3GarbLy5VdrAyEkrvayn5aWWB0VtcgdI95HRv6T71DyrYAKjZbgq84xEwmtnZCMM3MzeQNKh5xF/BjAgMBAAECgYBXI5+nDRxrxluI3GK2l+cT3LkUNt6VXshc05YGQTq+WXyi9Twsw9wgpOMiE2KWCJ0dOFdokSqyZWMU03zU/ueqclHe54R07DyC/3YIIGKq6pPi/wu1qBOCPNxf0kITcgBE/JKRb/c79o4srV3UlLXXi6LV4YcOQHf+NLFNb7+jcQJBAOmk+YjEj1Pow4hDoyngTx351bgLtl83VsFhxfmwooumzMNksp9jiWkPLAgtIDqwVvs4aZL/WmV65lgdmzCzXFUCQQCtL/4HmoGEBuwxUF7DhvVhuxxj2zBsUrL0l9+TnSfWChehNENoWwQTo8vggKrSEug/5V/EQkX9H+ZOU5C/xNHXAkEAtcIgWTRIJ8eQrSWo/b/A7JnZl8aMxj+/nsrX/2lY2fkVm/9vMa12TSN/ZpDsXJun3uFAyBkcEovsO6o0e0tczQJAOSYPE38+ocyPAC7fNnJAYsGVurXHotcfSmsbUeCYFp858O4IGFWAYOK6EhkjRTMMBJmyIlckNUTjgJE+wKk3/QJBAN/E05QAv8YlS8NVfqylS9OCcbuH+pSkYJHc14P7+cNG2mrcWh5Y10QWhV+aHruutOLTtBQBN71tsvUu2l3O4Go=
  rsaPublicKey: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCeEEnD3Qzqha9N9FHuBXQaC4N4scgN7PdlOTNMTkm2/g0nZQTueH0TxpsNYZKGR3kFAz/nWLD+STCUch32BY9MnFF/KZHtxmq2y8uVXawMhJK72sp+WllgdFbXIHSPeR0b+k+9Q8q2ACo2W4KvOMRMJrZ2QjDNzM3kDSoecRfwYwIDAQAB

---
#测试环境配置
spring:
  profiles: aliyun
  datasource:
    name: test
    url: jdbc:sqlserver://localhost:1433;databasename=zhouwx_szst
    username: sa
    password: Root123abc@hd
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
logging:
  config: classpath:logback-test.xml
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:18761/eureka/
gateway-config:
  rsaPrivateKey: MIICdwIBADANBgkqhkiG9w0BAQEFAASCAmEwggJdAgEAAoGBAJ4QScPdDOqFr030Ue4FdBoLg3ixyA3s92U5M0xOSbb+DSdlBO54fRPGmw1hkoZHeQUDP+dYsP5JMJRyHfYFj0ycUX8pke3GarbLy5VdrAyEkrvayn5aWWB0VtcgdI95HRv6T71DyrYAKjZbgq84xEwmtnZCMM3MzeQNKh5xF/BjAgMBAAECgYBXI5+nDRxrxluI3GK2l+cT3LkUNt6VXshc05YGQTq+WXyi9Twsw9wgpOMiE2KWCJ0dOFdokSqyZWMU03zU/ueqclHe54R07DyC/3YIIGKq6pPi/wu1qBOCPNxf0kITcgBE/JKRb/c79o4srV3UlLXXi6LV4YcOQHf+NLFNb7+jcQJBAOmk+YjEj1Pow4hDoyngTx351bgLtl83VsFhxfmwooumzMNksp9jiWkPLAgtIDqwVvs4aZL/WmV65lgdmzCzXFUCQQCtL/4HmoGEBuwxUF7DhvVhuxxj2zBsUrL0l9+TnSfWChehNENoWwQTo8vggKrSEug/5V/EQkX9H+ZOU5C/xNHXAkEAtcIgWTRIJ8eQrSWo/b/A7JnZl8aMxj+/nsrX/2lY2fkVm/9vMa12TSN/ZpDsXJun3uFAyBkcEovsO6o0e0tczQJAOSYPE38+ocyPAC7fNnJAYsGVurXHotcfSmsbUeCYFp858O4IGFWAYOK6EhkjRTMMBJmyIlckNUTjgJE+wKk3/QJBAN/E05QAv8YlS8NVfqylS9OCcbuH+pSkYJHc14P7+cNG2mrcWh5Y10QWhV+aHruutOLTtBQBN71tsvUu2l3O4Go=
  rsaPublicKey: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCeEEnD3Qzqha9N9FHuBXQaC4N4scgN7PdlOTNMTkm2/g0nZQTueH0TxpsNYZKGR3kFAz/nWLD+STCUch32BY9MnFF/KZHtxmq2y8uVXawMhJK72sp+WllgdFbXIHSPeR0b+k+9Q8q2ACo2W4KvOMRMJrZ2QjDNzM3kDSoecRfwYwIDAQAB
  